[package]
name = "software_racheta"
version = "0.1.0"
edition = "2024"
publish = false
build = "build.rs"

[dependencies]
atsamd-hal = { version = "0.23.4", features = ["samd21g"] }

cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"

panic-probe = { version = "1", features = ["print-defmt"] }
defmt = "1"
defmt-rtt = "1"

feather_m0 = { version = "0.20.4", features = ["usb", "express", "rt"] }
usb-device = "0.3"
usbd-serial = "0.2"
panic-halt = "1"
